const countries = [
  "Iceland",
  "Spain",
  "Iraq",
  "Malawi",
  "Hong Kong",
  "Malta",
  "Paraguay",
  "Djibouti",
  "Madagascar",
  "Nepal",
  "San Marino",
  "Netherlands",
  "Greenland",
  "Norway",
  "Tuvalu",
  "Lebanon",
  "Burkina Faso",
  "Cape Verde",
  "Gibraltar",
  "Algeria",
  "Georgia",
  "Mongolia",
  "Iran",
  "Tokelau",
  "Singapore",
  "French Guiana",
  "Martinique",
  "British Virgin Islands",
  "Nicaragua",
  "Moldova",
  "Yemen",
  "Gambia",
  "Kyrgyzstan",
  "Cuba",
  "Eritrea",
  "Svalbard and Jan Mayen",
  "El Salvador",
  "Timor-Leste",
  "South Korea",
  "Mali",
  "Turks and Caicos Islands",
  "Ghana",
  "Egypt",
  "Gabon",
  "Togo",
  "Taiwan",
  "Cook Islands",
  "Eswatini",
  "Oman",
  "Central African Republic",
  "Italy",
  "Uruguay",
  "Bahamas",
  "Brazil",
  "Myanmar",
  "Vatican City",
  "Sweden",
  "Vietnam",
  "Estonia",
  "Guinea-Bissau",
  "Aruba",
  "Palestine",
  "Peru",
  "Antigua and Barbuda",
  "Heard Island and McDonald Islands",
  "Burundi",
  "Jordan",
  "Pitcairn Islands",
  "Guatemala",
  "French Polynesia",
  "South Georgia",
  "Laos",
  "Sierra Leone",
  "India",
  "British Indian Ocean Territory",
  "Jamaica",
  "North Macedonia",
  "Canada",
  "Guam",
  "Norfolk Island",
  "Saint Kitts and Nevis",
  "Grenada",
  "Liberia",
  "United States",
  "Bahrain",
  "Germany",
  "Bermuda",
  "Malaysia",
  "Kiribati",
  "Ukraine",
  "Faroe Islands",
  "Afghanistan",
  "São Tomé and Príncipe",
  "Kuwait",
  "Poland",
  "Vanuatu",
  "Comoros",
  "American Samoa",
  "Niue",
  "China",
  "Western Sahara",
  "Panama",
  "Solomon Islands",
  "Costa Rica",
  "Papua New Guinea",
  "Japan",
  "South Sudan",
  "Marshall Islands",
  "Monaco",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Sint Maarten",
  "Venezuela",
  "Micronesia",
  "Montserrat",
  "Thailand",
  "Bouvet Island",
  "Anguilla",
  "Philippines",
  "New Zealand",
  "Saint Barthélemy",
  "Brunei",
  "Slovakia",
  "Republic of the Congo",
  "Wallis and Futuna",
  "New Caledonia",
  "Montenegro",
  "French Southern and Antarctic Lands",
  "Finland",
  "Liechtenstein",
  "Colombia",
  "Andorra",
  "Belize",
  "Bolivia",
  "Niger",
  "Russia",
  "Caribbean Netherlands",
  "Tanzania",
  "Zimbabwe",
  "Antarctica",
  "Azerbaijan",
  "Mauritius",
  "Armenia",
  "Czechia",
  "Haiti",
  "Sri Lanka",
  "Albania",
  "Morocco",
  "United States Virgin Islands",
  "Syria",
  "Bhutan",
  "Jersey",
  "Senegal",
  "Réunion",
  "Tunisia",
  "Switzerland",
  "Saint Pierre and Miquelon",
  "Luxembourg",
  "Samoa",
  "Austria",
  "Turkey",
  "Latvia",
  "United Arab Emirates",
  "Bosnia and Herzegovina",
  "Botswana",
  "Guernsey",
  "Seychelles",
  "Angola",
  "Australia",
  "Qatar",
  "Slovenia",
  "Namibia",
  "Saint Martin",
  "Equatorial Guinea",
  "Christmas Island",
  "Cambodia",
  "Guinea",
  "Dominica",
  "Cyprus",
  "Israel",
  "Ivory Coast",
  "Uzbekistan",
  "Zambia",
  "Somalia",
  "Bulgaria",
  "Rwanda",
  "Belgium",
  "Guyana",
  "Kosovo",
  "Mexico",
  "Denmark",
  "DR Congo",
  "Curaçao",
  "Ethiopia",
  "Macau",
  "Pakistan",
  "Indonesia",
  "Nauru",
  "Northern Mariana Islands",
  "United Kingdom",
  "Argentina",
  "Cameroon",
  "Romania",
  "Uganda",
  "France",
  "Suriname",
  "Maldives",
  "Fiji",
  "Greece",
  "Trinidad and Tobago",
  "Mauritania",
  "Tonga",
  "Chile",
  "Benin",
  "Sudan",
  "Chad",
  "Lesotho",
  "Saint Lucia",
  "Falkland Islands",
  "Lithuania",
  "Mozambique",
  "Tajikistan",
  "Cocos (Keeling) Islands",
  "North Korea",
  "Serbia",
  "United States Minor Outlying Islands",
  "Puerto Rico",
  "Honduras",
  "Kenya",
  "Portugal",
  "Belarus",
  "Dominican Republic",
  "Mayotte",
  "Palau",
  "Saudi Arabia",
  "Bangladesh",
  "Barbados",
  "Isle of Man",
  "Kazakhstan",
  "Libya",
  "Cayman Islands",
  "Nigeria",
  "Ireland",
  "South Africa",
  "Ecuador",
  "Guadeloupe",
  "Åland Islands",
  "Saint Vincent and the Grenadines",
  "Croatia",
  "Hungary",
  "Turkmenistan",
];

export default countries;
